In [1]:
import wittgenstein as lw
import pandas as pd
from inspect import currentframe, getframeinfo
from pandas.core.common import SettingWithCopyError
from wittgenstein import base
pd.options.mode.chained_assignment = 'raise'

In [2]:
df = pd.read_csv('/Users/ilanmoscovitz/Documents/Metis/Projects/local_lw/datasets/adult.csv')
#df = df.head(1000)

In [ ]:
df.sort_values('age')

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
4159,17,Private,130125,10th,6,Never-married,Other-service,Own-child,Amer-Indian-Eskimo,Female,1055,0,20,United-States,<=50K
18810,17,Private,187308,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,15,United-States,<=50K
25709,17,Private,153021,12th,8,Never-married,Sales,Own-child,White,Female,0,0,20,United-States,<=50K
6046,17,?,103810,12th,8,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
8682,17,?,127003,9th,5,Never-married,?,Own-child,Black,Male,0,0,40,United-States,<=50K
30359,17,Private,160029,11th,7,Never-married,Other-service,Other-relative,White,Female,0,0,22,United-States,<=50K
4458,17,Private,245918,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,12,United-States,<=50K
29417,17,Private,147069,10th,6,Never-married,Sales,Own-child,White,Female,0,0,16,United-States,<=50K
11757,17,Private,294485,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,30,United-States,<=50K
22875,17,Private,142964,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,<=50K
31107,17,Local-gov,192387,9th,5,Never-married,Other-service,Own-child,White,Male,0,0,45,United-States,<=50K
5991,17,Self-emp-not-inc,60116,10th,6,Never-married,Adm-clerical,Own-child,White,Male,0,0,10,United-States,<=50K
8579,17,Private,121037,12th,8,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,<=50K
22983,17,?,241021,12th,8,Never-married,?,Own-child,Other,Female,0,0,40,United-States,<=50K
31098,17,Private,169155,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,35,United-States,<=50K
25669,17,Private,202521,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,<=50K
11922,17,Private,154908,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,10,United-States,<=50K
23013,17,Private,205726,11th,7,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,<=50K
25639,17,Private,321880,10th,6,Never-married,Other-service,Own-child,Black,Male,0,0,15,United-States,<=50K
7028,17,?,110998,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Female,0,0,40,Philippines,<=50K
8518,17,Local-gov,246308,11th,7,Never-married,Prof-specialty,Own-child,White,Female,0,0,20,Puerto-Rico,<=50K
18518,17,?,34088,12th,8,Never-married,?,Own-child,White,Female,0,0,25,United-States,<=50K
27555,17,Private,160758,10th,6,Never-married,Sales,Other-relative,White,Male,0,0,30,United-States,<=50K
18498,17,Private,173807,11th,7,Never-married,Craft-repair,Own-child,White,Female,0,0,15,United-States,<=50K
18816,17,?,181337,10th,6,Never-married,?,Own-child,Other,Female,0,0,20,United-States,<=50K
25725,17,?,212125,10th,6,Never-married,?,Own-child,White,Female,0,0,20,United-States,<=50K
18856,17,Private,277112,11th,7,Never-married,Sales,Own-child,White,Male,0,0,30,United-States,<=50K
18888,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,<=50K
1235,17,Private,209949,11th,7,Never-married,Sales,Own-child,White,Female,0,1602,12,United-States,<=50K
11304,17,Private,111332,11th,7,Never-married,Sales,Own-child,White,Female,0,0,20,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,90,Private,221832,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K
21420,90,Private,226968,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
2299,90,Private,175491,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,9386,0,50,Ecuador,>50K
2296,90,Private,46786,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,9386,0,15,United-States,>50K
5134,90,Private,137018,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
2241,90,Self-emp-not-inc,155981,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,10566,0,50,United-States,<=50K
31799,90,?,313986,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,>50K
26259,90,?,175444,7th-8th,4,Separated,?,Not-in-family,White,Female,0,0,15,United-States,<=50K
20149,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,20,?,<=50K
1742,90,Private,87372,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,72,United-States,>50K
1739,90,Local-gov,227796,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,20051,0,60,United-States,>50K
15057,90,?,225063,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Male,0,0,10,South,<=50K
199,90,Private,51744,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,2206,40,United-States,<=50K
28999,90,Federal-gov,195433,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,30,United-States,<=50K
15505,90,Private,250832,10th,6,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K
3776,90,Self-emp-not-inc,82628,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,2964,0,12,United-States,<=50K
3854,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K
31218,90,Private,47929,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
16552,90,Local-gov,187749,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,20,Philippines,<=50K
23590,90,Private,52386,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K
9984,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
25339,90,?,166343,1st-4th,2,Widowed,?,Not-in-family,Black,Female,0,0,40,United-States,<=50K
17603,90,Private,90523,HS-grad,9,Widowed,Transport-moving,Unmarried,White,Male,0,0,99,United-States,<=50K
22166,90,Private,206667,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
8914,90,Private,51744,Masters,14,Never-married,Exec-managerial,Not-in-family,Black,Male,0,0,50,United-States,>50K
8791,90,Private,141758,9th,5,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
8645,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
7756,90,Private,313986,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
14659,90,Private,40388,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,55,United-States,<=50K
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K

In [ ]:
train = df.head(1000)
test = df.tail(10000)
irep = lw.IREP(verbosity=4)
irep.fit(train, class_feat='income', pos_class='>50K')

In [ ]:
end

In [ ]:
test_X = test.drop('income',axis=1)
test_X.head(1)
test_y = test['income']
irep.score(test_X, test_y)
#irep.predict(test_X)

In [ ]:
ripper = lw.RIPPER(verbosity=2)
ripper.fit(train, n_discretize_bins=3, class_feat='income', pos_class='>50K')
ripper.score(test_X, test_y)

In [ ]:
ripper.bin_transformer_

In [ ]:
def bar(df):
    def foo(df):
        bar_df = df.copy()
        bar_df['income']=bar_df['age']
        return bar_df
    df = foo(df)
bar(train)
train

In [ ]:
end

In [ ]:
#irep = lw.IREP()
#irep.fit(df, n_discretize_bins=10, class_feat='income', pos_class='>50K')

In [ ]:
#irep.ruleset_

In [ ]:
#from wittgenstein.base import bin_df
#bin_df(df, n_discretize_bins=10, ignore_feats=[], verbosity=0)[0]['age'].value_counts()

In [ ]:
df.head(1)

In [ ]:
irep.bin_transformer_

In [ ]:
import numpy as np
pd.cut(df['age'], bins=10).value_counts()

In [ ]:
bin_df

In [ ]:
len(df)

In [ ]:
train = df.head(1000)
test = df.tail(10000)
irep = lw.IREP(verbosity=2)
irep.fit(train, class_feat='income', pos_class='>50K')

In [ ]:
test_X = test.drop('income',axis=1)
test_y = test['income']
binned_X = base.bin_transform(test_X, irep.bin_transformer_, names_precision=2)
irep.score(test_X, test_y)
#irep.predict(test_X)

In [ ]:
test_X

In [ ]:
df = pd.read_csv('/Users/ilanmoscovitz/Documents/Metis/Projects/local_lw/datasets/house-votes-84.csv')

In [ ]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df)
irep = lw.IREP(verbosity=1)
irep.fit(train, class_feat='Party', pos_class='democrat')

In [ ]:
test_X = test.drop('Party',axis=1)
test_y = test['Party']
irep.score(test_X, test_y)